version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - export CI=false # Prevents tests from running automatically
      - npm install # Installs dependencies

  build:
    commands:
      - npm run build # Builds the Next.js app for static export

artifacts:
  base-directory: build # Upload only static files from 'build' directory
  files:
    - "**/*"
